# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 2.1.1
maven_group = me.mangregory.asr
archives_name = asr
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21

# Dependencies
architectury_api_version = 13.0.2
fabric_loader_version = 0.16.0
fabric_api_version = 0.100.7+1.21
neoforge_version = 21.0.113-beta
jei_version = 19.5.0.44
modmenu_version = 11.0.1