# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 3.1.0
maven_group = me.mangregory
archives_name = asr
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# Dependencies
architectury_api_version = 21.0.6
fabric_loader_version = 0.19.3
fabric_api_version = 0.155.2+26.2
neoforge_version = 26.2.0.32-beta
modmenu_version=20.0.1
jei_version=30.14.0.89
resourceful_config_version=26.2:5.0.0
