modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "asr"
version = "${version}"
displayName = "Asgard Shield: Reloaded"
authors = "ManGregory, ACGaming"
description = '''
A Hexxit mod ported over to new Minecraft Versions. Includes Giant Swords and Asgard Shields!
'''
logoFile = "asr.png"

[[dependencies.asr]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.asr]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.asr]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "asr.mixins.json"
