plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    developmentNeoForge.extendsFrom common
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    // Architectury API. This is optional, and you can comment it out if you don't need it.
    implementation "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"
    implementation "com.teamresourceful.resourcefulconfig:resourcefulconfig-neoforge-$rootProject.resourceful_config_version"

    common(project(path: ':common')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')

    // compile against the JEI API but do not include it at runtime
    // compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    // compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    // at runtime, use the full JEI jar for NeoForge
    // runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: inputs.properties.version
    }
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()       // Remove default source set inclusion
    from(zipTree(jar.archiveFile))     // Unpack jar output (preserves Loom modifications)

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = null           // shadowJar becomes the main artifact
}
